config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "messages#index"
  
  resources :messages, only: [:index] do
    get "send_page", on: :collection
    post "send_message", on: :collection
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < ApplicationController
  protect_from_forgery with: :null_session
  # before_action :authenticate

  def create
    mensaje = message_params[:text]
    if mensaje != ""
      Pusher.trigger('messages_channel', 'my-message', {
        message: message_params[:text]
      })
    end

    # @message = message_params 

    # render 'api/v1/create.js.erb', format: :js
  end

  private
    def message_params
      params.permit(:text)
    end

    def authenticate
      unless User.where(api_token: request.headers['HTTP_X_API_TOKEN']).exists? 
        head 401
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include MessagesHelper

  def index
  end

  def send_page
  end

  def send_message
    datos_tren_1 = Datum.where(train: "TN-2")
    #datos_tren_2 = Datum.where(train: "TN-1")

    datos_tren_1.each do |e|

      coords_train_1 = {
        lat: e.lat,
        lng: e.lng,
        speed: e.speed,
        train: "TA-12NT"
      }

      # segundo =  datos_tren_2[index]
      #
      # if segundo != nil
      #   coords_train_2 = {
      #     lat: segundo.lat,
      #     lng: segundo.lng,
      #     speed: segundo.speed,
      #     train: "TA-13NT"
      #   }
      # else
      # coords_train_2 = { lat: 0, lng: 0, speed: 0 }
      # end

      Pusher.trigger('messages_channel', 'my-message', {
        coords_train1: coords_train_1
      })

      sleep 1
      puts "Still running...."
    end

  end

  private
    def message_params
      params.require(:message).permit(:text)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/messages/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 text-center py-3 mt-3" style="height: auto; background-color: whitesmoke; border-radius: 5px;">
      <div class="space">
        <ul class="p-0" id="messages">
        </ul>
      </div>
    </div>
  </div>
</div>

<script src="https://js.pusher.com/4.1/pusher.min.js"></script>
<script>
  var pusher = new Pusher('2fc3ea72dbaa03b65735', {
    cluster: 'us2',
    encrypted: true
  });

  var channel = pusher.subscribe('messages_channel');
  channel.bind('my-message', function(data) {
    if (data.from == "<%= current_user.email %>") {
      $('#messages').append('<li class="my p-2">' + data.message + '</li>');
    } else {
      $('#messages').append('<li class="other p-2"><span class="mess">' + data.message + '<span class="by"> Send by:' + data.from +' </li>'); 
    }
  });
</script>

app/views/messages/send_message.js.erb
$('.control').val('');
$('#messages').append('<li class="my p-2">hola</li>');

app/views/messages/send_page.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 text-center mt-3" style="height: auto; background-color: whitesmoke; border-radius: 5px;">
      <%= form_for :message, url: send_message_messages_path, class:"", remote: true do |f| %>
        <%= f.submit "Send data", class: "btn btn-default my-5" %>
      <% end %>
      <%= link_to "Cancelar",send_page_messages_path, class:"" %>
    </div>
  </div>
</div>